name: Publish 7.2 FPM-Alpine Image
on: 
  push:
    paths: 
      - 'php7.2/fpm-alpine/**'
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish 7.2 fpm-alpine Docker Hub
        run: ./publish-image.sh -p
        shell: bash
        working-directory: ./php7.2/fpm-alpine/
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish 7.2 fpm-alpine to Github Package Registry
        run: ./publish-image.sh -g
        shell: bash
        working-directory: ./php7.2/fpm-alpine/ 
